import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { Counter } from '../lib/features/counter/counter';

import { Row, Col, Button } from 'antd'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Example title
        </h1>

        <p className={styles.description}>
          <Row justify="center">
            <Col span={12}>
              <Button type='primary'>Example antd button</Button>
            </Col>
            <Col>
              <Counter />
            </Col>
          </Row>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
